@startuml
!include estilo.iuml
mainframe sd Excluir vaga
autonumber "0:"
hide footbox

actor Empresa as E
boundary ":TelaVagas" as T
control ":EmpresaController" as C
entity ":VagaDAO" as D
E -> T ++ : clicar em "Excluir"
T --> E : "Deseja realmente excluir?"
E -> T : confirmar
T -> C ++ : vagas(acao = excluir, id)
C -> C : conferir permissão
C -> D ++ : excluir(id)
D --> C -- : true
C --> T -- : "Vaga excluída."
T --> E -- : exibir mensagem
@enduml
