@startuml
!include estilo.iuml
mainframe uc Candidatura
left to right direction
actor Candidato as C
rectangle "Conecta Vagas DF" {
  usecase "Candidatar-se à vaga" as CA
  usecase "Verificar limite\ndo plano" as VL
  usecase "Cancelar candidatura" as CC
  usecase "Acompanhar status\ne retorno" as AS
}
C -- CA
C -- CC
C -- AS
CA ..> VL : <<include>>
@enduml
