@startuml
!include estilo.iuml
mainframe uc Área da empresa
left to right direction
actor Empresa as E
rectangle "Conecta Vagas DF" {
  usecase "Atualizar status e\nretorno da candidatura" as ST
  usecase "Excluir candidatura" as EX
  usecase "Baixar currículo" as BC
  usecase "Consultar banco\nde talentos" as BT
  usecase "Manter perfil\nda empresa" as MP
}
actor Administrador as A
E -- ST
E -- BC
E -- BT
E -- MP
ST -- A
EX -- A
BC -- A
@enduml
