@startuml
!include estilo.iuml
mainframe uc Planos
left to right direction
actor Candidato as C
rectangle "Conecta Vagas DF" {
  usecase "Assinar plano\n(VIP / Premium)" as AP
  usecase "Cancelar assinatura" as CA
}
actor Empresa as E
C -- AP
C -- CA
AP -- E
CA -- E
@enduml
