@startuml
!include estilo.iuml
mainframe uc Manter categoria
left to right direction
actor Administrador as A
rectangle "Conecta Vagas DF" {
  usecase "Cadastrar categoria" as C
  usecase "Alterar categoria" as U
  usecase "Ativar / desativar\ncategoria" as T
  usecase "Excluir categoria" as E
}
A -- C
A -- U
A -- T
A -- E
@enduml
