@startuml
!include estilo.iuml
mainframe uc Gerenciar assinaturas
left to right direction
actor Administrador as A
rectangle "Conecta Vagas DF" {
  usecase "Consultar assinaturas\n(filtros e ordenação)" as L
  usecase "Conceder assinatura" as C
  usecase "Alterar assinatura\n(valor, datas, situação)" as U
  usecase "Cancelar assinatura" as X
  usecase "Excluir assinatura" as E
}
A -- L
A -- C
A -- U
A -- X
A -- E
@enduml
